- hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - vim

    - name: Install packages HA
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - haproxy
    
    - name: set /etc/haproxy/haproxy.cfg
      shell: |
        cat > /etc/haproxy/haproxy.cfg <<EOF
        global
        user haproxy
        group haproxy

        defaults
        mode http
        log global
        retries 2
        timeout connect 3000ms
        timeout server 5000ms
        timeout client 5000ms

        frontend kubernetes
        bind {{ frontend_ip }}:6443
        option tcplog
        mode tcp
        default_backend kubernetes-master-nodes 

        backend kubernetes-master-nodes
        mode tcp
        balance roundrobin
        option tcp-check
        server k8s-master-0 {{ master_node_ip_0 }}:6443 check fall 3 rise 2
        server k8s-master-1 {{ master_node_ip_1 }}:6443 check fall 3 rise 2
        server k8s-master-2 {{ master_node_ip_2 }}:6443 check fall 3 rise 2
        EOF

    - name: enable HA
      service:
        name: haproxy
        daemon_reload: yes
        state: restarted